name: scan-build

on: [push, pull_request]

jobs:
  scan-build:

    runs-on: ubuntu-22.04

    steps:
    - name: Install
      run: |
        sudo apt-get update -q
        sudo apt-get install clang-tools-14

    - uses: actions/checkout@v3

    - name: Scan-build
      run: |
        scan-build-14 --status-bugs -analyze-headers make -j`nproc`
